updated README.md

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -76,8 +76,12 @@ jobs:
 
       - name: Trust GPG Key
         run: |
-          KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons --fingerprint | awk -F: '/fpr:/ {print $10}')
-          echo "${KEY_FINGERPRINT}:6:" | gpg --batch --import-ownertrust
+          KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons --fingerprint | awk -F: '/^fpr:/ {print $10}')
+          if [[ -z "$KEY_FINGERPRINT" ]]; then
+            echo "Error: Failed to extract GPG key fingerprint."
+            exit 1
+          fi
+          echo "$KEY_FINGERPRINT:6:" | gpg --batch --import-ownertrust
 
       - name: Release to Maven Central
         run: |
